num = (input('Digite um numero com até 4 caracteres: '))
print('Unidade: {}'.format(num[3]))
print('Dezena: {}'.format(num[2]))
print('Centena: {}'.format(num [1]))
print('Milhar: {}'.format(num[0]))
