nome = str(input('Digite seu nome completo: ')).strip()
print ('Analisando seu nome, tenho as seguintes informações: ')
print ('Seu nome em maiusculas: {}'.format(nome.upper()))
print ('Seu nome em minusculas: {}'.format(nome.lower()))
print ('Seu nome tem exatamente: {} letras'.format(len(nome) - nome.count(' ')))
print ('Seu primeiro nome tem: {} letras'.format(nome.find(' ')))
